import type { Metadata } from 'next';

import BackLink from '@/components/BackLink';

export const metadata: Metadata = {
  title: { absolute: 'Privacy Policy — Empire Signal' },
  description:
    'How Empire Signal handles your data: what we collect, how word analyses are processed and cached, and how to delete your data.',
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-bg text-ink">
      <div className="mx-auto w-full max-w-2xl px-5 py-6 sm:px-8 sm:py-10">
        <BackLink className="text-xs text-ink-muted hover:text-accent transition-colors">
          ← Back to Empire Signal
        </BackLink>

        <header className="mt-8 mb-8">
          <h1
            className="text-3xl sm:text-4xl text-ink"
            style={{ fontFamily: 'var(--font-dm-serif)' }}
          >
            Privacy Policy
          </h1>
          <p className="mt-2 text-sm text-ink-faint">Last updated: July 5, 2026</p>
        </header>

        <div className="space-y-8 text-[15px] leading-relaxed text-ink-muted">
          <section>
            <h2 className="mb-2 text-lg font-semibold text-ink">Who we are</h2>
            <p>
              Empire Signal is built by a solo independent developer. For any
              privacy request, contact{' '}
              <a
                href="mailto:cesarabrahamhernandezponce@gmail.com"
                className="text-accent hover:text-accent-hover transition-colors"
              >
                cesarabrahamhernandezponce@gmail.com
              </a>
              .
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-ink">What we collect</h2>
            <p>
              If you create an account, we store your email and password through
              Supabase Auth. When you use the app, we keep the words and any
              optional context you submit for analysis. We also collect anonymized
              usage analytics to understand how the app is used.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-ink">Analytics</h2>
            <p>
              We use PostHog for analytics, including session replay — recordings
              of how you interact with the interface. This lets a solo developer
              find and fix bugs without a dedicated QA team.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-ink">AI processing</h2>
            <p>
              Word analyses are generated by third-party AI providers (Google
              Gemini and models via OpenRouter). On their free tiers, the text you
              submit may be used by those providers to improve their models.
              Please do not include personal or sensitive information in the word
              or context fields.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-ink">Caching</h2>
            <p>
              Word analyses are stored in a shared global cache so that other
              users benefit from work already done. Your personal search history
              stays private to your account.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-ink">Data deletion</h2>
            <p>
              You can delete your search history from within the app at any time.
              To delete your account entirely, send a request to{' '}
              <a
                href="mailto:cesarabrahamhernandezponce@gmail.com"
                className="text-accent hover:text-accent-hover transition-colors"
              >
                cesarabrahamhernandezponce@gmail.com
              </a>
              .
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-ink">Cookies</h2>
            <p>
              We only use functional cookies: those needed to keep you signed in
              (Supabase authentication sessions) and those used by our analytics.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
